language: node_js
node_js:
  - 0.10
  - 0.12

install:
  - npm install
  - pushd example && npm install && popd

script:
  - node --version && npm --version
  - npm run test-coverage
  - pushd example && node build.js && popd

after_script:
  - npm run codeclimate

deploy:
  provider: npm
  email: aymeric@beaumet.me
  api_key:
    secure: ElLpC/BFiBm4hKSfMTEHhZewoXeauhmdslaexC2b+Bg9y9mjJhdR+hhBgtWoY+hoIaBH2E+hDieRMNYCEnsANRo3BDzSJRF5dzsb61Ul13po9xJVz2ZIlhIePAUQLB/SAiDqlyLonDUdMr1iSw/l8t3T6iZ6iiblwX9f/XJ4WrY=
  on:
    repo: aymericbeaumet/metalsmith-concat
    branch: master
    tags: true

###

sudo: false

addons:
  code_climate:
    repo_token:
      secure: SmzRS/9BnajgeebIYSgB6g/EoyKWLNuuLROQULjjCR2BOqSL+TyngZb06yl0YQXcSTOStC2z/CtEttuORGB6iZ/Vp5Oo2qVcKRm2CAB4JVUGpi/EWPsMWfGRNQ6qXWVEluqEynme6lvK2mZTdqRFvE9Hvx4rXbLLOWy36LZXP0Y=
